cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    gcarvacho:
      email: lala@gmail.com
      name: Gianni
      password: $2b$12$kQ7opsriB5mEnTH311iLn.XhhUhPGLKZmTYi7HCJ6169GT.2WQyKW
    rocio:
      email: rocio@gmail.com
      name: ro
      password: $2b$12$o4FmzOmZc17EBw3VFUIuZ.2yB0vesuZmGvnEkPd.xXGwrrf8jb62m
preauthorized:
  emails: []
